### ISSUE TITLE
Add and Remove methods not working inside listData

### ISSUE THREAD

**Issue by bahdotsh** [persistenceOne/persistenceSDK#270] opened 2021-07-29 13:26 UTC

**Comment by puneet2019** [comment] 2021-07-30 12:15
Debugging the testCases, ListData once returned as types.Data is unable to convert it back to a list (slice/array)

**Comment by puneet2019** [comment] 2021-07-30 12:41
> Debugging the testCases, ListData once returned as types.Data is unable to convert it back to a list (slice/array),
> The zeroth index returns all the elements

This was resolved by removing extra wrapping on the Data, search in list data expected sdkAddressData

**Comment by puneet2019** [comment] 2021-07-31 02:42
The problem is the Search function: 
as pointed out in the docs: 
https://pkg.go.dev/sort#Search
```For instance, given a slice data sorted in ascending order, the call Search(len(data), func(i int) bool { return data[i] >= 23 }) returns the smallest index i such that data[i] >= 23. If the caller wants to find whether 23 is in the slice, it must test data[i] == 23 separately.```
which makes [checking for equal to in binary search](https://github.com/persistenceOne/persistenceSDK/blob/6d8e7c07adf476941759663394bb43d8189a6917/schema/types/base/sortedDataList.go#L22) invalid

**Closed** 2021-08-04 12:17 UTC
Labels: bug
